(function(NX) {
  NX.DOM = {
    output:          document.getElementById('output'),
    cmdInput:        document.getElementById('cmdInput'),
    statusL:         document.getElementById('statusLeft'),
    statusR:         document.getElementById('statusRight'),
    acHint:          document.getElementById('autocomplete'),
    bootOvl:         document.getElementById('bootOverlay'),
    bootTxt:         document.getElementById('bootText'),
    promptLbl:       document.getElementById('promptLabel'),
    statusDot:       document.getElementById('statusDot'),
    statusMode:      document.getElementById('statusMode'),
    progressFill:    document.getElementById('progressFill'),
    progressLabel:   document.getElementById('progressLabel'),
    progressTrack:   document.getElementById('progressTrack'),
    playbackBadge:   document.getElementById('playbackBadge'),
    btnRewind:       document.getElementById('btnRewind'),
    btnBack:         document.getElementById('btnBack'),
    btnPlay:         document.getElementById('btnPlay'),
    btnPause:        document.getElementById('btnPause'),
    btnStop:         document.getElementById('btnStop'),
    btnAhead:        document.getElementById('btnAhead'),
    btnFastFwd:      document.getElementById('btnFastFwd'),
    btnRecord:       document.getElementById('btnRecord'),
    modeToggle:      document.getElementById('modeToggle'),
    fontKnob:        document.getElementById('fontKnob'),
    fontKnobTooltip: document.getElementById('fontKnobTooltip'),
    stardateClock:   document.getElementById('stardateClock'),
    stardateDow:     document.getElementById('stardateDow'),
    stardateDate:    document.getElementById('stardateDate'),
    terminal:        document.querySelector('.terminal'),
  };
  NX.DOM.fontKnobMount = NX.DOM.fontKnob && NX.DOM.fontKnob.closest('.font-knob-mount');
})(window.NX = window.NX || {});
